imports:
    - { resource: parameters.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    app.controllers.get_youtube_videos:
        class: App\Controller\GetYoutubeVideosController
        arguments:
            - '@tactician.commandbus'

    App\UseCase\Query\GetYoutubeVideos\QueryHandler:
        tags:
            - { name: tactician.handler, typehints: true }

    App\Service\Google\OauthAuthenticator:
        arguments:
            - '@http_client'
            - '@cache.app'
            - '%google_client_id%'
            - '%google_client_secret%'

    App\Service\Youtube\GoogleApiClient:
        arguments:
            - '@http_client'
            - '@App\Service\Google\OauthAuthenticator'
            - '%google_api_key%'

    App\Service\Youtube\VideoSearchProvider:
        arguments:
            - '@App\Service\Youtube\GoogleApiClient'